### ISSUE TITLE
invalid Balatro.exe

### ISSUE THREAD

**Issue by aidoeoii903** [antipatico/balatromobile#12]
I'm trying to run a command to get the apk file out, I get an ERROR: invalid balatro.exe how to fix this problem? there any way 
![problem2](https://github.com/antipatico/balatromobile/assets/74287991/205eec9a-562d-4cda-b662-54a6e94491b6)

to solve this problem?

**Comment by antipatico** [comment]
You need to specify the full path to your Balatro.exe file. Usually it is in your Steam folder.
