### ISSUE TITLE
Invalid Balatro.exe 2

### ISSUE THREAD

**Issue by aidoeoii903** [antipatico/balatromobile#13]
I added the full path to it, but it did not give the apk file, the script did not want to be executed.
![problem3](https://github.com/antipatico/balatromobile/assets/74287991/58b67503-e9b6-4cf1-b1db-3dbd0e8a732f)

**Comment by antipatico** [comment]
Since there is no output, I would assume you have a balatro-VERSION.apk in your working directory (`C:\Users\clayb`)

**Comment by aidoeoii903** [comment]
> Поскольку выходных данных нет, я бы предположил, что у вас есть balatro-VERSION.apk в вашем рабочем каталоге (`C:\Users\clayb`)
He's there, thank you very much, I have another problem balatro crashes on my phone with an error in the game itself
