### ISSUE TITLE
Add new Pip build

### ISSUE THREAD

**Issue by jmriego** [antipatico/balatromobile#16]
First of all, thanks a lot for this program. It works just great and it's very easy to use and adapt if needed.

I was trying to create the .apk for my build of 1.0.1m-FULL but the publish Pip version doesn't work with that. I was able to make it work with the current code in this repo, but you might want to publish the latest version to make it easier and to be able to follow the README instructions that point to Pip currently.

Thanks!

**Comment by antipatico** [comment]
@jmriego Ideally we would setup a Github Action to do that, so that my intervention is not needed when merging requests. Do you want to try to do that? :)

**Comment by jmriego** [comment]
Sure thing! I have done this type of thing in the past but I never used `flit` before. I did some testing in my fork and this seems to work great.

I have just sent a PR with the process that depends on changes to the `__version__.py` but let me know if you'd prefer a different method of triggering that Github Action

**Comment by antipatico** [comment]
Merged and bumped to 0.6.0, I will delete the releases and leave the tags. Thanks for the contribution!

**Comment by jmriego** [comment]
sounds great. Thanks a lot!
