### ISSUE TITLE
Doesn't work on Fedora

### ISSUE THREAD

**Issue by Enderteck** [antipatico/balatromobile#2]
I tried using this script after installing it through pip and I get an error when I try to use it:

balatromobile android Balatro.exe
Traceback (most recent call last):
  File "/home/me/.local/bin/balatromobile", line 5, in <module>
    from balatromobile.gamble import main
  File "/home/me.local/lib/python3.12/site-packages/balatromobile/gamble.py", line 9, in <module>
    from tabulate import tabulate
ModuleNotFoundError: No module named 'tabulate'

I have python:

python3 --version
Python 3.12.2

JRE:

locate 'bin/java' | grep jre

/home/me/.local/share/Steam/steamapps/common/Mindustry/jre/bin/java
/home/me/.minecraft/runtime/jre-legacy/linux/jre-legacy/bin/java
/home/me/.minecraft/runtime/jre-legacy/linux/jre-legacy/bin/javaws

**Comment by antipatico** [comment]
Should be fixed as version 0.1.1

Update with `python3 -m pip install -U balatromobile`
Then, you can check the version with `balatromobile --version`

**Comment by Enderteck** [comment]
It works now thanks !
