### ISSUE TITLE
Getting the Java version with JRE V8 Update 411 on Windows fails

### ISSUE THREAD

**Issue by Ron-J1** [antipatico/balatromobile#7]
Hey,

apparently, on windows the arg to get the java version is `-version` ¯\_(ツ)_/¯ ["source"](https://stackoverflow.com/questions/37186197/errorcould-not-create-the-java-virtual-machine-errora-fatal-exception-has-occu).

So for my setup on Windows 11 with JRE Version 8 Update 411 I had to modify the `is_java_installed` function to 

```
def is_java_installed() -> bool:
    try:
        run_silent(["java", "-version"])
        return True
    except FileNotFoundError:
        return False
```

**Comment by antipatico** [comment]
`-version` works on my linux machine too. I will fix it eventually, or you can open an MR and I will merge it!
